# Generated by Django 4.0.1 on 2022-01-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Imagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=30)),
                ("foto", models.ImageField(upload_to="")),
                ("data", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
