# Generated by Django 4.0.1 on 2022-01-23 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="imagem",
            old_name="foto",
            new_name="imagem",
        ),
    ]
